#!/usr/bin/env python3
"""
build_review_register.py — Aggregate meta-analysis review status.

Scans meta-analyses/<slug>.md front matter and writes docs/review/REGISTER.md:
per problem, the four-model AI panel verdicts, whether the "AI-Reviewed (4-model)"
badge is earned (all four recorded, none `reject`), and the human-review status.
Split panels are surfaced, never hidden.

Stdlib + PyYAML.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
MA = ROOT / "meta-analyses"
OUT = ROOT / "docs" / "review" / "REGISTER.md"
MODELS = ["claude", "gpt", "gemini", "grok"]
SYMBOL = {
    "accept": "✅", "accept-with-revisions": "🟢", "major-revisions": "🟠",
    "reject": "❌", "pending": "·",
}


def front_matter(text: str) -> dict | None:
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        return yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return None


def badge(ai: dict) -> str:
    verdicts = [(ai.get(m) or {}).get("verdict", "pending") for m in MODELS]
    if any(v == "pending" for v in verdicts):
        return "⏳ in-panel"
    if any(v == "reject" for v in verdicts):
        return "❌ rejected"
    if len(set(verdicts)) > 1:
        return "🟡 4-model (split)"
    return "🏅 AI-Reviewed (4-model)"


def main() -> int:
    rows, counts = [], {"badged": 0, "in_panel": 0, "total": 0}
    if MA.exists():
        for md in sorted(MA.glob("*.md")):
            if md.name.lower() == "readme.md":
                continue
            fm = front_matter(md.read_text(encoding="utf-8"))
            if not fm:
                continue
            counts["total"] += 1
            ai = fm.get("ai_review", {}) or {}
            cells = " ".join(
                f"{m[0].upper()}{SYMBOL.get((ai.get(m) or {}).get('verdict','pending'),'?')}"
                for m in MODELS
            )
            b = badge(ai)
            if b.startswith("🏅"):
                counts["badged"] += 1
            elif b.startswith("⏳"):
                counts["in_panel"] += 1
            rows.append(
                f"| [{fm.get('title', md.stem)}](../../meta-analyses/{md.name}) "
                f"| {cells} | {b} | `{fm.get('human_review','pending')}` |"
            )

    body = [
        "# 🗒️ Meta-Analysis Review Register",
        "",
        "Auto-generated by `scripts/build_review_register.py`. Tracks the four-model "
        "AI review panel (**C**laude · **G**PT · **G**emini · **G**rok) and human-review "
        "status for every meta-analysis. See "
        "[AI-META-REVIEW.md](AI-META-REVIEW.md) for what the badge means.",
        "",
        f"**Badged AI-Reviewed (4-model):** {counts['badged']} · "
        f"**in panel:** {counts['in_panel']} · **total meta-analyses:** {counts['total']}",
        "",
        "Per-model symbols: ✅ accept · 🟢 accept-with-revisions · 🟠 major-revisions · "
        "❌ reject · · pending.",
        "",
        "| Meta-analysis | Panel (C/G/G/G) | Badge | Human review |",
        "|---------------|-----------------|-------|--------------|",
    ]
    body += rows or ["| _(no meta-analyses yet)_ | | | |"]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
    print(f"Register: {counts['total']} meta-analyses, {counts['badged']} badged -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
