#!/usr/bin/env python3
"""
generate.py — The Atlas build engine.

Single source of truth: data/problems.yaml
This script:
  1. Loads and validates every problem against schema/problem.schema.json
  2. Computes the Composite Severity Score (CSS) and the canonical ranking
  3. Emits data/problems.json (machine registry with computed fields)
  4. Emits RANKING.md (the full ranked table)
  5. Scaffolds problems/NNN-slug/ folders with dossier templates (idempotent;
     never overwrites human-written content — only creates what is missing)
  6. Refreshes the auto-generated ranking block inside README.md

Run:  python scripts/generate.py          (build everything)
      python scripts/generate.py --check  (validate + verify ranking is current)

Pure standard library except PyYAML + jsonschema (see requirements.txt).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required:  pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
REGISTRY_YAML = ROOT / "data" / "problems.yaml"
REGISTRY_JSON = ROOT / "data" / "problems.json"
SCHEMA = ROOT / "schema" / "problem.schema.json"
RANKING_MD = ROOT / "RANKING.md"
README = ROOT / "README.md"
PROBLEMS_DIR = ROOT / "problems"

README_BEGIN = "<!-- BEGIN:RANKING (auto-generated by scripts/generate.py — do not edit) -->"
README_END = "<!-- END:RANKING -->"

CURRENT_YEAR = 2025  # frozen reference year for reproducible age scoring


# --------------------------------------------------------------------------- #
#  Scoring
# --------------------------------------------------------------------------- #
def age_score(year_posed: int) -> float:
    """Older problems score higher. Saturates at 100 (~300 years old)."""
    age = CURRENT_YEAR - year_posed
    return max(0.0, min(100.0, age / 3.0))


def composite_severity(p: dict) -> float:
    """CSS — higher means 'harder + older + more central + less tractable'."""
    return round(
        0.40 * p["difficulty"]
        + 0.30 * p["centrality"]
        + 0.20 * age_score(p["year_posed"])
        + 0.10 * (100 - p["tractability"]),
        3,
    )


# --------------------------------------------------------------------------- #
#  Validation
# --------------------------------------------------------------------------- #
def validate(problems: list[dict]) -> list[str]:
    errors: list[str] = []
    slugs = set()
    try:
        import jsonschema  # type: ignore

        schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        validator = jsonschema.Draft202012Validator(schema)
    except ImportError:
        validator = None
        errors.append("WARN: jsonschema not installed; skipping schema validation.")

    for i, p in enumerate(problems):
        ctx = f"problem[{i}] ({p.get('slug', '?')})"
        if validator is not None:
            for err in validator.iter_errors(p):
                errors.append(f"{ctx}: schema: {err.message}")
        slug = p.get("slug")
        if slug in slugs:
            errors.append(f"{ctx}: duplicate slug '{slug}'")
        slugs.add(slug)
    return errors


# --------------------------------------------------------------------------- #
#  Templates (only written if the file does not already exist)
# --------------------------------------------------------------------------- #
def dossier_templates(p: dict, rank: int, css: float) -> dict[str, str]:
    title = p["title"]
    folder = p["slug"]  # stable, slug-only folder name (rank lives in metadata)
    origin = ", ".join(p["originators"])
    head = (
        f"# {title}\n\n"
        f"> **Atlas Rank #{rank}** · CSS **{css}** · Field: *{p['field']}* · "
        f"Posed: **{fmt_year(p['year_posed'])}** · Status: `{p['status']}`"
        + ("  · 🏛️ **Millennium Prize Problem**" if p["millennium_prize"] else "")
        + "\n\n"
    )
    return {
        "README.md": head
        + f"## Plain statement\n\n{p['statement_plain'].strip()}\n\n"
        + "## Dossier contents\n\n"
        + "| File | Contents |\n|------|----------|\n"
        + "| [`history.md`](history.md) | Origin, formulation, and timeline |\n"
        + "| [`originator.md`](originator.md) | Biography of the originator(s) |\n"
        + "| [`approaches.md`](approaches.md) | Major attack strategies and partial results |\n"
        + "| [`attempts.md`](attempts.md) | Notable attempts, near-misses, and false proofs |\n"
        + "| [`papers.md`](papers.md) | The 25 most important papers (old + new) |\n"
        + "| [`mathematicians.md`](mathematicians.md) | Top 10 contributors, past and present |\n"
        + "| [`status.md`](status.md) | Current frontier and what a proof would require |\n"
        + "| [`metadata.json`](metadata.json) | Machine-readable record |\n"
        + "| [`rag/`](rag/) | Chunked corpus for retrieval-augmented generation |\n\n"
        + f"*Originators: {origin}.*\n",
        "history.md": f"# History — {title}\n\n_Origin, formulation, and timeline._\n\n"
        "<!-- DOSSIER:history -->\n",
        "originator.md": f"# Originator(s) — {title}\n\n_Biography, background, and the ideas that led here._\n\n"
        "<!-- DOSSIER:originator -->\n",
        "approaches.md": f"# Approaches — {title}\n\n_Major strategies, partial results, and barriers._\n\n"
        "<!-- DOSSIER:approaches -->\n",
        "attempts.md": f"# Attempts — {title}\n\n_Notable attempts, near-misses, retracted proofs._\n\n"
        "<!-- DOSSIER:attempts -->\n",
        "papers.md": f"# Key Papers — {title}\n\n_The 25 most important papers. Each carries a verification flag._\n\n"
        "<!-- DOSSIER:papers -->\n",
        "mathematicians.md": f"# Top Mathematicians — {title}\n\n_Ten figures who shaped the problem, past and present._\n\n"
        "<!-- DOSSIER:mathematicians -->\n",
        "status.md": f"# Status & Frontier — {title}\n\n_Where the problem stands and what a resolution would require._\n\n"
        "<!-- DOSSIER:status -->\n",
        "metadata.json": json.dumps(
            {**p, "rank": rank, "css": css, "folder": folder}, indent=2, ensure_ascii=False
        )
        + "\n",
        "rag/.gitkeep": "",
    }


def fmt_year(y: int) -> str:
    return f"{abs(y)} BCE" if y < 0 else f"{y} CE" if y < 1000 else str(y)


# --------------------------------------------------------------------------- #
#  Emitters
# --------------------------------------------------------------------------- #
def ranking_table(ranked: list[tuple[int, float, dict]]) -> str:
    rows = [
        "| # | Problem | Field | Posed | CSS | Difficulty | Status | 🏛️ |",
        "|---|---------|-------|-------|-----|-----------|--------|----|",
    ]
    for rank, css, p in ranked:
        link = f"[{p['title']}](problems/{p['slug']}/README.md)"
        mp = "✅" if p["millennium_prize"] else ""
        rows.append(
            f"| {rank} | {link} | {p['field']} | {fmt_year(p['year_posed'])} "
            f"| {css} | {p['difficulty']} | `{p['status']}` | {mp} |"
        )
    return "\n".join(rows)


def write_ranking_md(ranked, meta):
    body = (
        "# 🏔️ The Master Ranking\n\n"
        f"_Atlas v{meta['version']} · {len(ranked)} problems · "
        "ranked hardest+oldest → most tractable by Composite Severity Score (CSS)._\n\n"
        "See [docs/methodology/RANKING.md](docs/methodology/RANKING.md) for the formula.\n\n"
        + ranking_table(ranked)
        + "\n\n> CSS = 0.40·difficulty + 0.30·centrality + 0.20·age + 0.10·(100−tractability).\n"
    )
    RANKING_MD.write_text(body, encoding="utf-8")


def patch_readme(ranked):
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    block = README_BEGIN + "\n\n" + ranking_table(ranked) + "\n\n" + README_END
    if README_BEGIN in text and README_END in text:
        pre = text.split(README_BEGIN)[0]
        post = text.split(README_END)[1]
        README.write_text(pre + block + post, encoding="utf-8")


TEMPLATE_MARKER = "<!-- DOSSIER:"


def _is_unauthored(folder: Path) -> bool:
    """A folder is 'unauthored' if every section file still holds its template
    marker (or no section files exist). Such folders are safe to remove."""
    section_files = list(folder.glob("*.md"))
    if not section_files:
        return True
    for md in section_files:
        if md.name == "README.md":
            continue
        if TEMPLATE_MARKER not in md.read_text(encoding="utf-8"):
            return False
    return True


def reconcile(desired_slugs: set[str]) -> tuple[int, list[str]]:
    """Remove orphan folders (slug no longer in registry) that are unauthored;
    warn about authored orphans so human work is never silently deleted."""
    import shutil

    removed, warnings = 0, []
    if not PROBLEMS_DIR.exists():
        return 0, warnings
    for folder in PROBLEMS_DIR.iterdir():
        if not folder.is_dir() or folder.name in desired_slugs:
            continue
        if _is_unauthored(folder):
            shutil.rmtree(folder)
            removed += 1
        else:
            warnings.append(
                f"orphan folder '{folder.name}' has authored content but no registry "
                f"entry — left in place; rename its slug or remove manually."
            )
    return removed, warnings


def scaffold(ranked):
    created = 0
    for rank, css, p in ranked:
        folder = PROBLEMS_DIR / p["slug"]
        for rel, content in dossier_templates(p, rank, css).items():
            path = folder / rel
            if path.exists():
                # Always keep metadata.json fresh (it is fully generated).
                if rel == "metadata.json":
                    path.write_text(content, encoding="utf-8")
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            created += 1
    return created


# --------------------------------------------------------------------------- #
#  Main
# --------------------------------------------------------------------------- #
def main() -> int:
    ap = argparse.ArgumentParser(description="Build the Unsolved Mathematics Atlas.")
    ap.add_argument("--check", action="store_true", help="validate only; non-zero exit on problems")
    args = ap.parse_args()

    data = yaml.safe_load(REGISTRY_YAML.read_text(encoding="utf-8"))
    meta = data["meta"]
    problems = data["problems"]

    errors = validate(problems)
    hard_errors = [e for e in errors if not e.startswith("WARN")]
    for e in errors:
        print(("  " if e.startswith("WARN") else "ERROR: ") + e, file=sys.stderr)
    if hard_errors:
        return 1

    ranked = sorted(problems, key=composite_severity, reverse=True)
    ranked = [(i + 1, composite_severity(p), p) for i, p in enumerate(ranked)]

    if args.check:
        print(f"OK: {len(problems)} problems validated; ranking is computable.")
        return 0

    REGISTRY_JSON.write_text(
        json.dumps(
            {
                "meta": meta,
                "problems": [{**p, "rank": r, "css": c} for r, c, p in ranked],
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    write_ranking_md(ranked, meta)
    desired = {p["slug"] for _, _, p in ranked}
    removed, warnings = reconcile(desired)
    for w in warnings:
        print("  WARN: " + w, file=sys.stderr)
    created = scaffold(ranked)
    patch_readme(ranked)

    if removed:
        print(f"Reconciled: removed {removed} orphan folder(s).")
    print(f"Built {len(ranked)} problems · scaffolded {created} new files.")
    print(f"  -> {REGISTRY_JSON.relative_to(ROOT)}")
    print(f"  -> {RANKING_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
